[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Karnak = "cd156443-31ad-4f6f-850f-a93ee5f75905"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
Colors = "0.10, 0.11, 0.12, 0.13"
CSV = "0.10"
DataFrames = "1.6"
Documenter = "1.3"
Graphs = "1.9, 1.10, 1.11, 1.12, 1.13"
julia = "1.9"
NetworkLayout = "0.4.10"
SimpleWeightedGraphs = "1.5"
